FROM timescale/timescaledb:latest-pg16

# Install OpenSSL and sudo
RUN apk update && apk add --no-cache openssl sudo certbot

# Allow the postgres user to execute certain commands as root without a password
RUN echo "postgres ALL=(root) NOPASSWD: /bin/chmod, /usr/bin/certbot" > /etc/sudoers.d/postgres

# Add init scripts while setting permissions
COPY --chmod=755 init-ssl.sh /docker-entrypoint-initdb.d/init-ssl.sh
COPY --chmod=755 wrapper.sh /usr/local/bin/wrapper.sh

# Set up the Certbot renewal cron job
RUN echo "0 0 * * 0 certbot renew" >> /etc/crontab

# Override the ENTRYPOINT with a wrapper script
ENTRYPOINT ["wrapper.sh"]

EXPOSE 80 443

# Start postgres listening on port 5432
CMD ["postgres", "--port=5432"]