name: Docker Image CI/CD for number versions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    strategy:
      matrix:
        dockerfile:
          [
            "self-signed/Dockerfile.16",
            "self-signed/Dockerfile.17",
            "certbot/Dockerfile.16",
            "certbot/Dockerfile.17",
          ]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from Dockerfile name
        id: extract_version
        run: |
          dockerfile="${{ matrix.dockerfile }}"
          path="${dockerfile%/Dockerfile.*}"
          version_type="-${dockerfile%/Dockerfile.*}"
          version_type="${version_type#-self-signed}"
          version="${dockerfile#*Dockerfile.}"
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "type=${version_type}" >> $GITHUB_OUTPUT
          echo "path=${path}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build and Publish
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:${{ steps.extract_version.outputs.path }}"
          file: "Dockerfile.${{ steps.extract_version.outputs.version }}"
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository }}${{ steps.extract_version.outputs.type }}:${{ steps.extract_version.outputs.version }}
